# Generated by Django 5.0.6 on 2026-07-08 19:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('academic', '0003_alter_perioddefinition_options_and_more'),
        ('schools', '0001_initial'),
        ('subjects', '0001_initial'),
        ('teachers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TimetableEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day_of_week', models.PositiveSmallIntegerField(choices=[(0, 'Monday'), (1, 'Tuesday'), (2, 'Wednesday'), (3, 'Thursday'), (4, 'Friday'), (5, 'Saturday'), (6, 'Sunday')])),
                ('period_number', models.PositiveSmallIntegerField()),
                ('is_double', models.BooleanField(default=False)),
                ('is_practical', models.BooleanField(default=False)),
                ('class_instance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academic.class')),
                ('room', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='academic.room')),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='schools.school')),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academic.section')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academic.academicsession')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='subjects.subject')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='teachers.teacher')),
            ],
            options={
                'indexes': [models.Index(fields=['class_instance', 'section', 'day_of_week', 'period_number'], name='timetable_t_class_i_22ed72_idx'), models.Index(fields=['teacher', 'day_of_week', 'period_number'], name='timetable_t_teacher_93c491_idx')],
                'unique_together': {('school', 'session', 'class_instance', 'section', 'day_of_week', 'period_number')},
            },
        ),
    ]
