# Generated by Django 5.0.6 on 2026-07-09 19:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academic', '0003_alter_perioddefinition_options_and_more'),
        ('subjects', '0001_initial'),
        ('teachers', '0004_alter_teacher_preferred_days_and_more'),
        ('timetable', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubstituteAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('period_number', models.PositiveSmallIntegerField()),
                ('note', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('absent_teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='absences', to='teachers.teacher')),
                ('class_instance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academic.class')),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academic.section')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='subjects.subject')),
                ('substitute_teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='substitutions', to='teachers.teacher')),
            ],
            options={
                'unique_together': {('absent_teacher', 'date', 'period_number', 'class_instance', 'section')},
            },
        ),
    ]
