# Generated by Django 5.0.6 on 2026-07-12 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timetable', '0002_substituteassignment'),
    ]

    operations = [
        migrations.AddField(
            model_name='timetableentry',
            name='is_fixed',
            field=models.BooleanField(default=False),
        ),
    ]
