# Generated by Django 5.0.6 on 2026-07-21 01:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academic', '0006_delete_timetableversion'),
        ('schools', '0001_initial'),
        ('timetable', '0003_timetableentry_is_fixed'),
    ]

    operations = [
        migrations.CreateModel(
            name='TimetableVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.DateTimeField(auto_now=True)),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='schools.school')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academic.academicsession')),
            ],
            options={
                'unique_together': {('school', 'session')},
            },
        ),
    ]
