# Generated by Django 5.0.6 on 2026-08-08 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timetable', '0004_timetableversion'),
    ]

    operations = [
        migrations.AddField(
            model_name='timetableentry',
            name='combined_group_id',
            field=models.CharField(blank=True, help_text='Unique ID pairing joint sections together', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='timetableentry',
            name='is_combined',
            field=models.BooleanField(default=False, help_text='True if this period is shared with another section/class'),
        ),
    ]
