# Generated by Django 5.0.6 on 2026-08-13 19:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('schools', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('SCHOOL_ADMIN', 'School Admin / Principal'), ('COORDINATOR', 'Timetable Coordinator'), ('TEACHER', 'Teacher'), ('STUDENT', 'Student / Parent')], default='STUDENT', max_length=20)),
                ('phone_number', models.CharField(blank=True, max_length=15)),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_profiles', to='schools.school')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
