# Generated by Django 5.0.6 on 2026-07-07 18:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academic', '0001_initial'),
        ('schools', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PeriodDefinition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wing', models.CharField(choices=[('Junior', 'Junior'), ('Middle', 'Middle'), ('Senior', 'Senior')], max_length=10)),
                ('period_number', models.PositiveSmallIntegerField()),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('duration_minutes', models.PositiveSmallIntegerField()),
                ('is_assembly', models.BooleanField(default=False)),
                ('is_lunch', models.BooleanField(default=False)),
                ('is_break', models.BooleanField(default=False)),
                ('break_duration', models.PositiveSmallIntegerField(default=0)),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='period_definitions', to='schools.school')),
            ],
            options={
                'ordering': ['wing', 'period_number'],
                'unique_together': {('school', 'wing', 'period_number')},
            },
        ),
    ]
