# Generated by Django 5.0.6 on 2026-07-08 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academic', '0002_perioddefinition'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='perioddefinition',
            options={},
        ),
        migrations.AlterUniqueTogether(
            name='perioddefinition',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='perioddefinition',
            name='day_of_week',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(0, 'Monday'), (1, 'Tuesday'), (2, 'Wednesday'), (3, 'Thursday'), (4, 'Friday'), (5, 'Saturday'), (6, 'Sunday')], help_text='Leave blank for all days, or select a specific day for exceptions.', null=True),
        ),
        migrations.AddField(
            model_name='perioddefinition',
            name='special_activity',
            field=models.CharField(blank=True, help_text='e.g., MPT, Yoga, Games, Library', max_length=100, null=True),
        ),
    ]
