# Generated by Django 5.0.6 on 2026-07-12 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academic', '0003_alter_perioddefinition_options_and_more'),
        ('schools', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='perioddefinition',
            options={'ordering': ['wing', 'period_number']},
        ),
        migrations.AlterUniqueTogether(
            name='perioddefinition',
            unique_together={('school', 'wing', 'period_number')},
        ),
        migrations.AddField(
            model_name='perioddefinition',
            name='days',
            field=models.JSONField(blank=True, default=list, help_text='List of day numbers (0=Mon..6=Sun). Leave empty for all days.'),
        ),
        migrations.RemoveField(
            model_name='perioddefinition',
            name='day_of_week',
        ),
    ]
