# Generated by Django 5.0.6 on 2026-07-21 01:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('academic', '0005_timetableversion'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TimetableVersion',
        ),
    ]
