# Generated by Django 5.0.6 on 2026-08-10 01:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academic', '0006_delete_timetableversion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='section',
            name='working_days',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
