# Generated by Django 5.0.6 on 2026-08-10 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academic', '0007_alter_section_working_days'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perioddefinition',
            name='days',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AlterField(
            model_name='section',
            name='name',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='section',
            name='wing',
            field=models.CharField(blank=True, choices=[('Junior', 'Junior'), ('Middle', 'Middle'), ('Senior', 'Senior')], max_length=20),
        ),
    ]
