# Generated by Django 5.0.6 on 2026-08-13 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academic', '0008_alter_perioddefinition_days_alter_section_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perioddefinition',
            name='duration_minutes',
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
    ]
