# Generated by Django 5.0.6 on 2026-08-13 19:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('academic', '0009_alter_perioddefinition_duration_minutes'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='section',
            options={'ordering': ['class_instance__display_order', 'name']},
        ),
    ]
