# Generated by Django 5.0.6 on 2026-07-07 17:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('schools', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=20)),
                ('name', models.CharField(max_length=100)),
                ('is_optional', models.BooleanField(default=False)),
                ('requires_lab', models.BooleanField(default=False)),
                ('requires_practical', models.BooleanField(default=False)),
                ('min_gap_periods', models.PositiveSmallIntegerField(default=0)),
                ('max_gap_periods', models.PositiveSmallIntegerField(default=99)),
                ('default_double_period_allowed', models.BooleanField(default=False)),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='schools.school')),
            ],
            options={
                'unique_together': {('school', 'code')},
            },
        ),
    ]
