# Generated by Django 5.0.6 on 2026-07-10 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subjects', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='subject',
            name='color',
            field=models.CharField(default='#6c757d', help_text='Hex colour code (e.g., #FF5733)', max_length=7),
        ),
    ]
