# Generated by Django 5.0.6 on 2026-07-21 01:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('subjects', '0002_subject_color'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='subject',
            options={'ordering': ['name', 'code']},
        ),
    ]
