# Generated by Django 5.0.6 on 2026-07-08 19:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('academic', '0003_alter_perioddefinition_options_and_more'),
        ('schools', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('employee_id', models.CharField(max_length=50, unique=True)),
                ('mobile', models.CharField(max_length=15)),
                ('email', models.EmailField(max_length=254)),
                ('designation', models.CharField(max_length=100)),
                ('department', models.CharField(blank=True, max_length=100)),
                ('max_daily_load', models.PositiveSmallIntegerField(default=8)),
                ('max_weekly_load', models.PositiveSmallIntegerField(default=40)),
                ('is_class_teacher', models.BooleanField(default=False)),
                ('is_co_class_teacher', models.BooleanField(default=False)),
                ('preferred_periods', models.JSONField(default=list)),
                ('preferred_days', models.JSONField(default=list)),
                ('unavailable_days', models.JSONField(default=list)),
                ('unavailable_periods', models.JSONField(default=list)),
                ('half_day', models.BooleanField(default=False)),
                ('late_arrival', models.TimeField(blank=True, null=True)),
                ('early_departure', models.TimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('class_teacher_for', models.ForeignKey(blank=True, help_text='If this teacher is a class teacher, select the class.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='class_teachers', to='academic.class')),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='schools.school')),
            ],
        ),
        migrations.CreateModel(
            name='TeacherSubjectAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weekly_periods', models.PositiveSmallIntegerField()),
                ('is_primary', models.BooleanField(default=False)),
                ('preference_weight', models.FloatField(default=1.0)),
                ('class_subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teacher_assignments', to='academic.classsubject')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subject_assignments', to='teachers.teacher')),
            ],
            options={
                'unique_together': {('teacher', 'class_subject')},
            },
        ),
    ]
