# Generated by Django 5.0.6 on 2026-07-08 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teachers', '0002_alter_teacher_email_alter_teacher_employee_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacher',
            name='designation',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
