# Generated by Django 5.0.6 on 2026-07-08 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teachers', '0003_alter_teacher_designation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacher',
            name='preferred_days',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='preferred_periods',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='unavailable_days',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='unavailable_periods',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
