# Generated by Django 5.0.6 on 2026-08-08 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academic', '0006_delete_timetableversion'),
        ('teachers', '0004_alter_teacher_preferred_days_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='teachersubjectassignment',
            name='combined_group_name',
            field=models.CharField(blank=True, help_text="Required for combined classes. Use a unique label per group (e.g. 'Drawing-Standards').", max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='teachersubjectassignment',
            name='is_combined',
            field=models.BooleanField(default=False, help_text='Check if this subject is taught as a joint/combined period across multiple classes/sections.'),
        ),
        migrations.AddField(
            model_name='teachersubjectassignment',
            name='target_sections',
            field=models.ManyToManyField(blank=True, help_text='Leave empty to assign to ALL sections of this class. Select specific sections to limit this assignment.', related_name='teacher_assignments', to='academic.section'),
        ),
    ]
