# Generated by Django 5.0.6 on 2026-07-07 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='School',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='logos/')),
                ('board', models.CharField(choices=[('CBSE', 'CBSE'), ('ICSE', 'ICSE'), ('STATE', 'State Board'), ('OTHER', 'Other')], default='CBSE', max_length=20)),
                ('affiliation_no', models.CharField(max_length=50, unique=True)),
                ('udise_code', models.CharField(max_length=20, unique=True)),
                ('school_code', models.CharField(max_length=20, unique=True)),
                ('address', models.TextField()),
                ('city', models.CharField(max_length=100)),
                ('district', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=100)),
                ('pin_code', models.CharField(max_length=10)),
                ('principal_name', models.CharField(max_length=255)),
                ('vice_principal_name', models.CharField(blank=True, max_length=255)),
                ('academic_coordinator', models.CharField(blank=True, max_length=255)),
                ('exam_incharge', models.CharField(blank=True, max_length=255)),
                ('session_start', models.DateField()),
                ('session_end', models.DateField()),
                ('opening_time', models.TimeField()),
                ('closing_time', models.TimeField()),
                ('contact_number', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('website', models.URLField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
    ]
