# Generated by Django 5.0.6 on 2026-09-03 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='school',
            name='session_end',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='school',
            name='session_start',
            field=models.DateField(blank=True, null=True),
        ),
    ]
